# Generated by Django 5.0.6 on 2024-06-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_images_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='file_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
