# Generated by Django 5.0.6 on 2024-06-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_images_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='file_path',
        ),
    ]
