# Generated by Django 5.0.6 on 2024-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_images_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='file_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
