# Generated by Django 5.0.6 on 2024-08-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_changes_remove_images_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='gallery.tags'),
        ),
    ]
