# Generated by Django 5.0.6 on 2024-08-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_tags_images_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_type',
            field=models.CharField(choices=[('location', 'Location'), ('time', 'Time'), ('misc', 'Miscellaneous')], default='MISC', max_length=10),
            preserve_default=False,
        ),
    ]
